# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ttsfreeinsta

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_58a3be102b5645bfbe70972b1f586caf }}
        password: ${{ secrets.AzureAppService_ContainerPassword_32dab0b86d6841ed90a8242200c1fdb6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_58a3be102b5645bfbe70972b1f586caf }}/teste:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ttsfreeinsta'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bae7b355db7945fa97dd57b998ab13c7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_58a3be102b5645bfbe70972b1f586caf }}/teste:${{ github.sha }}'