# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ttsfreeinsta

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_ed1921d206a94777b86c8f959de4c9e0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f7a652a0bb194b6eb8c8a30662c98c6a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ed1921d206a94777b86c8f959de4c9e0 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ttsfreeinsta'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_938566b22a484e7ebefa9043c896f58e }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_ed1921d206a94777b86c8f959de4c9e0 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'